### PR TITLE
Update add assets

### PR DESCRIPTION
**Pull request by xdefrag**
- update mainnet assets list
- change address to Montelibero related tokens
- add exception handling to assets fetching

### CODE REVIEW

**Review by sondreb — DISMISSED** [review]
Changes look good 👍

**Comment by sozidatel** [comment]
@xdefrag может добавить BTCMTL?

**Comment by troggy** [comment]
@xdefrag I get CORS error for 
https://ticker-testnet.kamni.io/assets.json

I'm running Solar as a web app and use ngrok for https: https://c919-62-4-58-18.ngrok-free.app/index.dev.html

**Comment by xdefrag** [comment]
@sozidatel added BTCMTL and MTLAP

@troggy thanks for ngrok, fixed it

Снимок экрана 2024-01-11 в 21 39 59

**Review by troggy — APPROVED** [review]
assets.json is loaded now for me 👍🏼 

search is not working though: always returns nothing. Probably not a problem with this PR

**Pull request merged**
